function merge

diff --git a/executable_dot_zsh_functions b/executable_dot_zsh_functions
--- a/executable_dot_zsh_functions
+++ b/executable_dot_zsh_functions
@@ -396,12 +396,12 @@ function extract_file_from_image(){
 }
 
 function is_installed_by_brew(){
-    # Check if the file exists
-    local file="$1"
-    if [[ ! -e "$file" ]]; then
-      # Return an exit code without closing the shell while having -e set.
-      echo "File $file does not exist." && (exit 1)
-    fi
+  # Check if the file exists
+  local file="$1"
+  if [[ ! -e "$file" ]]; then
+    # Return an exit code without closing the shell while having -e set.
+    echo "File $file does not exist." && (exit 1)
+  fi
 
   if (( ${+commands[rg]} )) && (( ${+commands[brew]} )); then
     # Count the number of lines in the file
@@ -419,7 +419,6 @@ function is_installed_by_brew(){
     echo "Requires ripgrep and brew to be installed." && (exit 1)
   fi
 }
-<<<<<<< HEAD
 
 function select_from_brew_info() {
   # Select fields from brew info JSON of installed homebrew formulas.
@@ -457,45 +456,42 @@ function select_from_brew_info() {
   duckdb -c "${query}"
   bat $query_rslt_path
 }
-||||||| fc4f6a7
-=======
 
 function print_pr_basics(){
-    if (( ${+commands[gh]} )); then
-        gh pr view $1 --json number,title,url,state,labels --template \
-        '[#{{ .number }}] {{.title}}
-            {{.state}} | {{.url}}
-            {{.labels | join ", "}}
-        '
-        exit 0
-    else
-        echo "Requires gh to be installed." && (exit 1)
-        exit 1
-    fi
+  if (( ${+commands[gh]} )); then
+      gh pr view $1 --json number,title,url,state,labels --template \
+      '[#{{ .number }}] {{.title}}
+          {{.state}} | {{.url}}
+          {{.labels | join ", "}}
+      '
+      exit 0
+  else
+      echo "Requires gh to be installed." && (exit 1)
+      exit 1
+  fi
 }
 
 function print_pr_failed_checks(){
-    local template='
-    {{- range . }}
-      {{- if eq .state "FAILURE" }}
-        {{ .name }} | {{ .description }}
-      {{- end }}
+  local template='
+  {{- range . }}
+    {{- if eq .state "FAILURE" }}
+      {{ .name }} | {{ .description }}
     {{- end }}
-    '
-    if (( ${+commands[gh]} )); then
-        gh pr checks $1 --json name,description,state --template $template | bat --plain
-        exit 0
-    else
-        echo "Requires gh to be installed." && (exit 1)
-        exit 1
-    fi
+  {{- end }}
+  '
+  if (( ${+commands[gh]} )); then
+      gh pr checks $1 --json name,description,state --template $template | bat --plain
+      exit 0
+  else
+      echo "Requires gh to be installed." && (exit 1)
+      exit 1
+  fi
 }
 
 function print_pr_review_request(){
-    local ask="Please review the following PR:"
-    local header=$(print_pr_basics)
-    local body=$(print_pr_failed_checks)
-    local msg="$ask\n$header\n$body"
-    echo -e "$msg"
+  local ask="Please review the following PR:"
+  local header=$(print_pr_basics)
+  local body=$(print_pr_failed_checks)
+  local msg="$ask\n$header\n$body"
+  echo -e "$msg"
 }
->>>>>>> 3d5ca50dddca4e350e720fb88346431827e75faa
